### Perceptrons in Neural Network

A Perceptron is the simplest form of a neural network that makes decisions by combining inputs with weights and applying an activation function. It is mainly used for binary classification problems. It forms the basic building block of many deep learning models.

The core components:

- **Inputs $(x_1,x_2,...,x_n)$:** These are the features or measurable attributes of a data point that the perceptron uses to make a decision. Each input provides a signal that contributes to the final output.**Example**: For an OR gate, the inputs are binary: $(x_1,x_2)∈{(0,1)}^2$. Inputs themselves have no inherent influence unless multiplied by weights.
- **Weights $(w_1,w_2,...,w_n)$:** Weights determine how strongly each input contributes to the prediction. A larger weight means the corresponding input has a higher impact. Weights are learned during training, adjusting based on errors. They act like importance scores for each feature.
- **Bias ($*b*$):** The bias is a constant value added to the weighted sum to shift the decision boundary. It allows the perceptron to classify correctly even when all input features are zero. Bias ensures the model is not forced to pass the decision boundary through the origin.

The simplified workflow:

- Compute the Weighted Sum: $z =∑_{i=1}^nw_ix_i+b$
- Apply the Activation Function: **Step function** (classic perceptron); Sigmoid, Tanh, ReLU
- Compare Prediction with Actual Output: $error = y - \hat{y}$
- Update the Weights (Learning Rule): $*w_i ← w_i+η(y−\hat{y})x_i*$
- Update the Bias Term: $b ← b+η(y−\hat{y})x_i$
- Repeat for All Samples Across Multiple Epochs
- Final Prediction: $*\hat{y} =step(w^⊤x+b)*$

In [222]:
# Perceptrons in Neural Network
import pandas as pd
import numpy as np


data = {
    "prio": [120,110,115,100,125,105,118,102,122,108],
    "static_prio": [120,110,115,100,120,105,118,102,120,108],
    "normal_prio": [120,110,115,100,125,105,118,102,122,108],
    "policy": [0,1,0,1,0,1,0,1,0,1],
    "vm_pgoff": [1024,4096,2048,8192,512,6000,1500,7000,900,5000],
    "class": [0,1,0,1,0,1,0,1,0,1]
}

df = pd.DataFrame(data)
X = df.drop(columns="class")
y = df["class"]

# The matrix X is the input to the MLP
X = X.values
y = y.values

**Step 1: Compute the Weighted Sum**

Each neuron receives inputs from the previous layer. It multiplies each input by its corresponding weight, adds them together, and then adds a bias.

Since we most likely use vector, the formula introduced above will become: $z = w^T x + b$

We repeat this computation across all samples. For example:

- After computing for sample 1: $z_1^{(1)}; z_2^{(1)}; z_3^{(1)}; z_4^{(1)}$
- We move on to sample 2: $z_1^{(2)}; z_2^{(2)}; z_3^{(2)}; z_4^{(2)}$
- Until sample  $j$: $z_1^{(j)}; z_2^{(j)}; z_3^{(j)}; z_4^{(j)}$
- Since we have 10 samples → This stops at $j = 10$

In [223]:
# Normalize the input features
X = (X - X.mean(axis=0)) / X.std(axis=0)

# Weights: 4 neurons × 5 features
W = np.array([
    [0.02, 0.01, 0.015, 0.5, 0.0005],
    [0.03, 0.02, 0.01, 0.4, 0.0003],
    [0.01, 0.015, 0.02, 0.6, 0.0007],
    [0.025, 0.02, 0.012, 0.45, 0.0004]
])
b = np.array([0.1, 0.1, 0.1, 0.1])
Z = np.zeros((len(X), len(W)))

# Compute z_k = (w_k^T * x) + b
for i in range(len(X)):
  print(f"Sample {i + 1}")
  for j in range(len(W)):
    z_k = np.dot(W[j], X[i]) + b[j]
    print(f"\t+ Neuron {j + 1}: {z_k}")
    # Append to the matrix
    Z[i][j] = z_k

print("Output Matrix Z:\n", Z)

Sample 1
	+ Neuron 1: -0.35779228441754873
	+ Neuron 2: -0.24201644853625212
	+ Neuron 3: -0.456976769366381
	+ Neuron 4: -0.29482585461986777
Sample 2
	+ Neuron 1: 0.5871148067277472
	+ Neuron 2: 0.4831451266829804
	+ Neuron 3: 0.6874424829092901
	+ Neuron 4: 0.5340666115688854
Sample 3
	+ Neuron 1: -0.3854348916275757
	+ Neuron 2: -0.27949335259624086
	+ Neuron 3: -0.4849017571242903
	+ Neuron 4: -0.33045654375163114
Sample 4
	+ Neuron 1: 0.5322142034383929
	+ Neuron 2: 0.40842208524142265
	+ Neuron 3: 0.6321309629764507
	+ Neuron 4: 0.4631129222099184
Sample 5
	+ Neuron 1: -0.3367979760234099
	+ Neuron 2: -0.21797075600378416
	+ Neuron 3: -0.4390338451105711
	+ Neuron 4: -0.27260714645909023
Sample 6
	+ Neuron 1: 0.5596374621129427
	+ Neuron 2: 0.4457673801801251
	+ Neuron 3: 0.6597488627846921
	+ Neuron 4: 0.4985681325133
Sample 7
	+ Neuron 1: -0.36883685748755646
	+ Neuron 2: -0.2569997282718457
	+ Neuron 3: -0.46812930672994024
	+ Neuron 4: -0.3090681544213706
Sample 8
	+ Neuron 

**Step 2: Activation Function**

The sigmoid function converts any real value into a number between 0 and 1, which can be interpreted as a probability: $\sigma(z)=\frac{1}{1+e^{-z}}$

In [224]:
# Sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Apply sigmoid to the weighted-sum matrix
H = sigmoid(Z)

print("Hidden Layer Output (After Sigmoid):\n", H)

Hidden Layer Output (After Sigmoid):
 [[0.4114941  0.43978949 0.38770326 0.42682283]
 [0.64270287 0.61849028 0.66539775 0.63043108]
 [0.40481674 0.43057799 0.38109532 0.41812954]
 [0.62999939 0.60070946 0.65297249 0.61375239]
 [0.4165875  0.44572204 0.39197121 0.43226716]
 [0.63636865 0.60963242 0.65920397 0.62212278]
 [0.40882211 0.43610138 0.38505911 0.42334221]
 [0.63253891 0.60427854 0.65545281 0.61709774]
 [0.41353293 0.44216279 0.38941347 0.42900148]
 [0.64018118 0.61496002 0.66293529 0.62712172]]


**Backpropagation**

We have already had the matrix $Z$ (Output Matrix) and $H$ (Hidden Layer Output after Sigmoid).

Instead of just a plain $error = y - \hat{y}$ → Neural networks usually compute a more common **loss function:**

- For regression problems → We use Mean Squared Error (MSE)

$MSE=\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2$

- For classification → We use Binary-Cross Entropy (BCE)

$L=-\frac{1}{n}\sum_{i=1}^{n}[y_i\log(\hat{y}_i)+(1-y_i)\log(1-\hat{y}_i)]$

→ BCE strongly penalizes **confident but wrong predictions**.

The goal of training an MLP is to minimize the loss function by adjusting the network's weights and biases. This is when Backpropagation is introduced → For familiarity, we use Gradient Descent: $w=w−η⋅\frac{∂L}{∂w}$

We will apply **Backpropagation for this problem.** The hidden layer has **4 neurons**, so the output neuron must have **4 weights**.

For sample i: $z_{out}^{(i)} =
w_1 h_1^{(i)} +
w_2 h_2^{(i)} +
w_3 h_3^{(i)} +
w_4 h_4^{(i)} +
b_{out}$

We do not need an explicit iteration when computing `z_out = np.dot(H, W_out) + b_out` because the operation is **vectorized**.

In this network, the hidden layer contains **four neurons**, while the output layer contains **only one neuron**. As a result, the output layer requires only **one set of weights**, represented as the vector $W_{out}$.

- The hidden layer output matrix H has the shape $10 \times 4$, meaning there are **10 samples and 4 hidden neuron activations per sample**.
- When we perform the dot product $H \cdot W_{out}$, NumPy automatically multiplies each row of $H$ with the weight vector $W_{out}$. This produces a vector of **10 values**, where each value corresponds to $z_{out}^{(i)}$ for one sample.
- In other words, the matrix multiplication internally performs the repeated computation for all samples at once, eliminating the need for a manual loop.
- This vectorized computation is possible because the hidden layer has **multiple neurons**, while the output layer has **a single neuron**, allowing the weight parameters to be represented as a single vector rather than a matrix.

**Step 3: Compute the Output Weighted Sum + Final Prediction**

In [225]:
W_out = [0.5, 0.3, 0.4, 0.6]
b_out = 0.1

# Compute Output Weighted Sum
z_out = np.dot(H, W_out) + b_out
print("z_out:\n", z_out)

z_out:
 [0.8488589  1.25131627 0.83489762 1.22465297 0.85815914 1.23802931
 0.84327044 1.22999279 0.85258158 1.24602575]


Apply the sigmoid activation to convert `z_out` into probabilities.

In [226]:
y_hat = sigmoid(z_out)

print("Predicted probabilities:")
print(y_hat)

Predicted probabilities:
[0.70032772 0.77752763 0.69738951 0.77288135 0.7022759  0.7752208
 0.69915356 0.77381731 0.70110841 0.77661114]


**Step 4: Compute Binary Cross Entropy Loss**

In [227]:
def binary_cross_entropy(y, y_hat):
    eps = 1e-9  # prevent log(0)
    loss = -np.mean(y * np.log(y_hat + eps) +
                   (1 - y) * np.log(1 - y_hat + eps))
    return loss

loss = binary_cross_entropy(y, y_hat)

print("Loss:", loss)

Loss: 0.7293900487551646


For sigmoid + binary cross entropy, a convenient simplification occurs:

$\frac{\partial L}{\partial z_{out}} = \hat{y} - y$

So we compute:

In [228]:
dz = y_hat - y

**Step 5: Gradient for Output Weights**

Recall:

$z_{out} = HW_{out} + b$

The gradient becomes:

$\frac{\partial L}{\partial W_{out}} =
\frac{1}{n} H^T (\hat{y} - y)$

In [229]:
n = len(y)

dW_out = np.dot(H.T, dz) / n
db_out = np.mean(dz)

Gradient Descent Update using the rule:

$w = w - \eta \frac{\partial L}{\partial w}$

In [230]:
learning_rate = 0.01

W_out = W_out - learning_rate * dW_out
b_out = b_out - learning_rate * db_out
print("Updated W_out:", W_out)
print("Updated b_out:", b_out)

Updated W_out: [0.49927637 0.29914891 0.39938605 0.59920831]
Updated b_out: 0.09762368667473544


**Step 6: Wrap It Into a Backpropagation Function**

In [231]:
def backprop_output_layer(H, y, W_out, b_out, lr=0.01):
    # Forward pass
    z_out = np.dot(H, W_out) + b_out
    y_hat = sigmoid(z_out)

    # Error gradient
    dz = y_hat - y
    n = len(y)
    # Gradients
    dW = np.dot(H.T, dz) / n
    db = np.mean(dz)

    # Update
    W_out -= lr * dW
    b_out -= lr * db
    return W_out, b_out, y_hat

In [232]:
W_out, b_out, y_hat = backprop_output_layer(H, y, W_out, b_out)
print("Updated W_out:", W_out)
print("Updated b_out:", b_out)
print("Predicted y:", y_hat)

Updated W_out: [0.49855667 0.29830175 0.39877603 0.59842056]
Updated b_out: 0.09525488851278673
Predicted y: [0.69956653 0.7767872  0.69662909 0.77213793 0.70151428 0.77447885
 0.69839267 0.77307447 0.70034704 0.7758701 ]


Implementing Adam in Python

We will apply Adam to update $W_{out}$ and $b_{out}$ using the gradients computed earlier.

In [233]:
# Adam parameters
lr = 0.01
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

# Adam parameters
m_w_out = np.zeros_like(W_out)
v_w_out = np.zeros_like(W_out)

m_b_out = 0
v_b_out = 0

m_w_h = np.zeros_like(W)
v_w_h = np.zeros_like(W)

m_b_h = np.zeros_like(b)
v_b_h = np.zeros_like(b)

t = 1

In [234]:
def adam_update(W, b, dW, db, m_w, v_w, m_b, v_b, t,
                lr=0.01, beta1=0.9, beta2=0.999, eps=1e-8):

    # Update biased first moment
    m_w = beta1 * m_w + (1 - beta1) * dW
    m_b = beta1 * m_b + (1 - beta1) * db
    # Update biased second moment
    v_w = beta2 * v_w + (1 - beta2) * (dW ** 2)
    v_b = beta2 * v_b + (1 - beta2) * (db ** 2)
    # Bias correction
    m_w_hat = m_w / (1 - beta1 ** t)
    v_w_hat = v_w / (1 - beta2 ** t)
    m_b_hat = m_b / (1 - beta1 ** t)
    v_b_hat = v_b / (1 - beta2 ** t)
    # Parameter update
    W = W - lr * m_w_hat / (np.sqrt(v_w_hat) + eps)
    b = b - lr * m_b_hat / (np.sqrt(v_b_hat) + eps)

    return W, b, m_w, v_w, m_b, v_b

Applying Adam After Backpropagation

In [235]:
epochs = 100

for epoch in range(epochs):

    # Forward pass
    z_out = np.dot(H, W_out) + b_out
    y_hat = sigmoid(z_out)

    # Compute loss
    loss = binary_cross_entropy(y, y_hat)

    # Backpropagation
    dz_out = y_hat - y

    # Output layer gradients
    dW_out = np.dot(H.T, dz) / len(y)
    db_out = np.mean(dz)
    dH = np.outer(dz_out, W_out)
    dZ = dH * H * (1 - H)

    # Hidden layer gradients
    dW = np.dot(dZ.T, X) / len(X)
    db = np.mean(dZ, axis=0)

    # Adam optimization to update the Output Weight and Bias
    W_out, b_out, m_w, v_w, m_b, v_b = adam_update(
        W_out, b_out,
        dW_out, db_out,
        m_w, v_w, m_b, v_b,
        t)

    W, b, m_w_h, v_w_h, m_b_h, v_b_h = adam_update(
        W, b,
        dW, db,
        m_w_h, v_w_h, m_b_h, v_b_h,
        t)

    t += 1

    if epoch % 10 == 0: # Print loss every 100 epochs
        print(f"Epoch {epoch}, Loss: {loss}")

Epoch 0, Loss: 0.7278191856195532
Epoch 10, Loss: 0.7126601084349518
Epoch 20, Loss: 0.701661796723429
Epoch 30, Loss: 0.6910096998980363
Epoch 40, Loss: 0.6808632760621441
Epoch 50, Loss: 0.6718507482690107
Epoch 60, Loss: 0.6647406582312877
Epoch 70, Loss: 0.6603365814102364
Epoch 80, Loss: 0.6594332364565535
Epoch 90, Loss: 0.6627924153973236


In [236]:
print("Optimized W_out:", W_out)
print("Optimized b_out:", b_out)

Optimized W_out: [ 0.1521855  -0.04806942  0.05240485  0.25204938]
Optimized b_out: -0.2511162988989904


In [238]:
# Final forward pass with trained weights
z_out = np.dot(H, W_out) + b_out
y_hat = sigmoid(z_out)

print("Final predicted probabilities:")
print(y_hat)
predictions = (y_hat >= 0.5).astype(int)
print("Predicted classes:")
print(predictions)
# Also show actual classes to compare
print("Actual classes:")
print(y)

Final predicted probabilities:
[0.47957754 0.50268325 0.47880118 0.50119989 0.48009815 0.50194405
 0.47926676 0.50149691 0.47978593 0.50238895]
Predicted classes:
[0 1 0 1 0 1 0 1 0 1]
Actual classes:
[0 1 0 1 0 1 0 1 0 1]
